export const mockArtists = [
  {
    id: "artist-1",
    name: "Ayo Balogun",
    image: null,
    accountType: "ARTIST",
    verified: true,
    bio: "Afrobeats artist from Lagos. Making waves across the continent.",
    location: "Lagos, Nigeria",
    profileColor: "#16a34a",
    followers: 24500,
    genre: "Afrobeats",
  },
  {
    id: "artist-2",
    name: "Amara Osei",
    image: null,
    accountType: "ARTIST",
    verified: true,
    bio: "Highlife meets modern soul. Ghana to the world.",
    location: "Accra, Ghana",
    profileColor: "#f59e0b",
    followers: 18200,
    genre: "Highlife",
  },
  {
    id: "artist-3",
    name: "Zuri Ndlovu",
    image: null,
    accountType: "ARTIST",
    verified: false,
    bio: "Amapiano producer and DJ. South African underground.",
    location: "Johannesburg, SA",
    profileColor: "#6366f1",
    followers: 9800,
    genre: "Amapiano",
  },
  {
    id: "artist-4",
    name: "Kwame Mensah",
    image: null,
    accountType: "ARTIST",
    verified: true,
    bio: "Spoken word poet & musician. Art is resistance.",
    location: "Nairobi, Kenya",
    profileColor: "#ef4444",
    followers: 12400,
    genre: "Spoken Word",
  },
  {
    id: "artist-5",
    name: "Fatou Diallo",
    image: null,
    accountType: "ARTIST",
    verified: false,
    bio: "R&B vocalist blending West African rhythms with neo-soul.",
    location: "Dakar, Senegal",
    profileColor: "#c084fc",
    followers: 7600,
    genre: "R&B",
  },
  {
    id: "artist-6",
    name: "Tendai Moyo",
    image: null,
    accountType: "ARTIST",
    verified: true,
    bio: "Electronic music producer. Afro-futurist soundscapes.",
    location: "Harare, Zimbabwe",
    profileColor: "#06b6d4",
    followers: 15300,
    genre: "Electronic",
  },
];

export const mockContent = [
  {
    id: "content-1",
    title: "Lagos Nights",
    description: "A vibe for the city that never sleeps",
    type: "AUDIO",
    genre: "Afrobeats",
    mood: "hype",
    plays: 145200,
    likes: 8900,
    comments: 342,
    duration: 234,
    isPremium: false,
    createdAt: new Date("2026-04-15"),
    artist: mockArtists[0],
  },
  {
    id: "content-2",
    title: "Golden Coast",
    description: "Highlife reimagined for a new generation",
    type: "VIDEO",
    genre: "Highlife",
    mood: "uplifting",
    plays: 89700,
    likes: 5400,
    comments: 198,
    duration: 312,
    isPremium: false,
    createdAt: new Date("2026-04-20"),
    artist: mockArtists[1],
  },
  {
    id: "content-3",
    title: "Midnight Piano",
    description: "Deep amapiano cuts for the late night sessions",
    type: "AUDIO",
    genre: "Amapiano",
    mood: "chill",
    plays: 67300,
    likes: 4100,
    comments: 156,
    duration: 278,
    isPremium: false,
    createdAt: new Date("2026-05-01"),
    artist: mockArtists[2],
  },
  {
    id: "content-4",
    title: "Words of Fire",
    description: "Spoken word piece about identity and heritage",
    type: "VIDEO",
    genre: "Spoken Word",
    mood: "dark",
    plays: 34500,
    likes: 2800,
    comments: 445,
    duration: 420,
    isPremium: true,
    createdAt: new Date("2026-05-05"),
    artist: mockArtists[3],
  },
  {
    id: "content-5",
    title: "Sahel Dreams",
    description: "Neo-soul melodies from the heart of West Africa",
    type: "AUDIO",
    genre: "R&B",
    mood: "calm",
    plays: 28900,
    likes: 2100,
    comments: 89,
    duration: 256,
    isPremium: false,
    createdAt: new Date("2026-05-08"),
    artist: mockArtists[4],
  },
  {
    id: "content-6",
    title: "Neon Savanna",
    description: "Afro-futurist electronic journey",
    type: "VIDEO",
    genre: "Electronic",
    mood: "hype",
    plays: 56100,
    likes: 3700,
    comments: 234,
    duration: 345,
    isPremium: false,
    createdAt: new Date("2026-05-10"),
    artist: mockArtists[5],
  },
  {
    id: "content-7",
    title: "Sunrise in Accra",
    description: "Acoustic session recorded at dawn",
    type: "AUDIO",
    genre: "Afro-Pop",
    mood: "uplifting",
    plays: 41200,
    likes: 3200,
    comments: 112,
    duration: 198,
    isPremium: false,
    createdAt: new Date("2026-05-11"),
    artist: mockArtists[1],
  },
  {
    id: "content-8",
    title: "Township Groove",
    description: "Heavy bass, township flavor",
    type: "AUDIO",
    genre: "Gqom",
    mood: "hype",
    plays: 72000,
    likes: 5100,
    comments: 278,
    duration: 267,
    isPremium: false,
    createdAt: new Date("2026-04-28"),
    artist: mockArtists[2],
  },
];

export const mockStreams = [
  {
    id: "stream-1",
    title: "Live from the Studio - New Album Preview",
    isLive: true,
    isPremium: false,
    viewerCount: 1247,
    thumbnailUrl: null,
    streamer: mockArtists[0],
    startedAt: new Date(Date.now() - 3600000),
  },
  {
    id: "stream-2",
    title: "Amapiano Mix Session",
    isLive: true,
    isPremium: false,
    viewerCount: 834,
    thumbnailUrl: null,
    streamer: mockArtists[2],
    startedAt: new Date(Date.now() - 7200000),
  },
  {
    id: "stream-3",
    title: "Exclusive: Behind the Scenes",
    isLive: false,
    isPremium: true,
    viewerCount: 0,
    thumbnailUrl: null,
    streamer: mockArtists[1],
    scheduledAt: new Date(Date.now() + 86400000),
  },
  {
    id: "stream-4",
    title: "Poetry Night - Open Mic",
    isLive: false,
    isPremium: false,
    viewerCount: 0,
    thumbnailUrl: null,
    streamer: mockArtists[3],
    scheduledAt: new Date(Date.now() + 172800000),
  },
];

export const mockProducts = [
  {
    id: "product-1",
    title: "Lagos Nights Hoodie",
    description: "Limited edition merch",
    price: 45.00,
    type: "MERCH",
    image: null,
    seller: mockArtists[0],
  },
  {
    id: "product-2",
    title: "Beat Pack Vol. 1",
    description: "10 original Amapiano beats",
    price: 25.00,
    type: "DIGITAL",
    image: null,
    seller: mockArtists[2],
  },
  {
    id: "product-3",
    title: "Golden Coast Vinyl",
    description: "Limited pressing, signed",
    price: 35.00,
    type: "MERCH",
    image: null,
    seller: mockArtists[1],
  },
  {
    id: "product-4",
    title: "Spoken Word Collection",
    description: "Digital poetry book + audio",
    price: 15.00,
    type: "DIGITAL",
    image: null,
    seller: mockArtists[3],
  },
  {
    id: "product-5",
    title: "Afro-Futurist Art Print",
    description: "High quality art print, A3 size",
    price: 20.00,
    type: "MERCH",
    image: null,
    seller: mockArtists[5],
  },
  {
    id: "product-6",
    title: "Sahel Dreams Stems",
    description: "Full stems for remixing",
    price: 30.00,
    type: "DIGITAL",
    image: null,
    seller: mockArtists[4],
  },
];

export const mockMessages = [
  {
    id: "msg-1",
    sender: mockArtists[0],
    lastMessage: "Thanks for the support! New music coming soon 🎵",
    time: new Date(Date.now() - 600000),
    unread: 2,
  },
  {
    id: "msg-2",
    sender: mockArtists[2],
    lastMessage: "Let's collab on the next track",
    time: new Date(Date.now() - 3600000),
    unread: 0,
  },
  {
    id: "msg-3",
    sender: mockArtists[4],
    lastMessage: "The recording session was amazing!",
    time: new Date(Date.now() - 7200000),
    unread: 1,
  },
];

export const mockGroups = [
  {
    id: "group-1",
    name: "Afrobeats Producers",
    description: "Connect with Afrobeats producers worldwide",
    memberCount: 2340,
    image: null,
  },
  {
    id: "group-2",
    name: "Lagos Music Scene",
    description: "Everything happening in Lagos music",
    memberCount: 5670,
    image: null,
  },
  {
    id: "group-3",
    name: "Amapiano Lovers",
    description: "The home of Amapiano",
    memberCount: 8900,
    image: null,
  },
  {
    id: "group-4",
    name: "African Poetry Circle",
    description: "Spoken word and poetry community",
    memberCount: 1200,
    image: null,
  },
];

export const mockStatusPosts = [
  {
    id: "status-1",
    user: mockArtists[0],
    text: "Studio session running late tonight. New heat loading... 🔥",
    createdAt: new Date(Date.now() - 1800000),
  },
  {
    id: "status-2",
    user: mockArtists[1],
    text: "Accra → Lagos. Tour life continues. See you at the show!",
    createdAt: new Date(Date.now() - 5400000),
  },
  {
    id: "status-3",
    user: mockArtists[2],
    text: "New amapiano set dropping this weekend. Who's ready?",
    createdAt: new Date(Date.now() - 10800000),
  },
  {
    id: "status-4",
    user: mockArtists[3],
    text: "Words have power. Never forget that.",
    createdAt: new Date(Date.now() - 21600000),
  },
];
